config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  root 'addresses#new'
  get '/:hashid' => 'addresses#redirect'
end

app/models/address.rb
class Address < ActiveRecord::Base
  validates :url, :url => true, :length => { :maximum => 500 }
  after_create :generate_hashid

  private
    def generate_hashid
      hashids = Hashids.new("this is my salt")
      self.hashid = hashids.encode(self.id)
      self.save()
    end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def redirect
    @address = Address.find_by(hashid: params[:hashid])
    redirect_to @address.url
  end

  def show
    @address = Address.find(params[:id])
    @url = "#{request.base_url}/#{@address.hashid}"
  end

  def create
    @address = Address.new(address_params)
    @address.save ? redirect_to(@address) : render('new')
  end

  private
  def address_params
    params.require(:address).permit(:url, :id, :hashid)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
<h1>Add your new url</h1>
<% if !@address.nil? %>
  <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    <%@address.errors.full_messages.each do |msg| %>
      <%= msg %><br/>
    <% end %>
  </div>
<% end %>

<%= form_for :address, url: addresses_path do |f| %>
  <p>
    <%= f.text_field :url,  placeholder: "http://just_type_your_super_long_url_here_and_we_will_shorten_it", class: 'input-large' %>
  </p>
  <p>
    <%= f.submit class: 'btn btn-primary' %>
  </p>
<% end %>
</div>
</div>

app/views/addresses/show.html.erb
<h4>Your new url is :</h4>

<h1><a href="<%= @url%>" target="_blank"><%= @url %></a></h1>
<h5><a href="/">Add another one ?</a></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Short Url App</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Short Url App", '/', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Add a url",  "/"  %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>